"""项目对官方 RoboDojo 的薄适配层。

官方任务、资产和 DP/ACT 等上游策略仍只存在于
``third_party/RoboDojo``。本包只放项目需要的 GUI、数据格式和策略协议适配，
避免把上游实现复制到 ``source``。
"""

from .data import (
    ROBODOJO_CAPTURE_ROOT,
    ROBODOJO_DEMO_ROOT,
    ROBODOJO_OFFICIAL_ROOT,
    ROBODOJO_SOURCE_LAYOUT_ROOT,
    TASK_CANDIDATES,
    RoboDojoPaths,
    RoboDojoPolicyCandidate,
    RoboDojoPolicyDemonstrations,
    RoboDojoRobotCandidate,
    RoboDojoSceneCandidate,
    RoboDojoTaskCandidate,
    audit_robodojo_capture,
    collect_robodojo_results,
    demonstration_environment_config_for,
    download_robodojo_assets,
    download_robodojo_demonstrations,
    ensure_runtime_env_config,
    environment_config_for,
    load_robodojo_policy_demonstrations,
    prepare_robodojo_runtime,
    reconstruct_push_t_source_layout,
    robodojo_resource_catalog,
    robodojo_status,
    robodojo_task_candidates,
    robodojo_task_catalog,
    sync_robodojo_official_snapshot,
    write_robodojo_paper_table,
)

__all__ = [
    "ROBODOJO_CAPTURE_ROOT",
    "ROBODOJO_DEMO_ROOT",
    "ROBODOJO_OFFICIAL_ROOT",
    "ROBODOJO_SOURCE_LAYOUT_ROOT",
    "RoboDojoPaths",
    "RoboDojoPolicyCandidate",
    "RoboDojoPolicyDemonstrations",
    "RoboDojoRobotCandidate",
    "RoboDojoSceneCandidate",
    "RoboDojoTaskCandidate",
    "TASK_CANDIDATES",
    "audit_robodojo_capture",
    "collect_robodojo_results",
    "demonstration_environment_config_for",
    "download_robodojo_assets",
    "download_robodojo_demonstrations",
    "ensure_runtime_env_config",
    "environment_config_for",
    "load_robodojo_policy_demonstrations",
    "prepare_robodojo_runtime",
    "reconstruct_push_t_source_layout",
    "robodojo_resource_catalog",
    "robodojo_status",
    "robodojo_task_candidates",
    "robodojo_task_catalog",
    "sync_robodojo_official_snapshot",
    "write_robodojo_paper_table",
]
